// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/about/advisory-board" | "/about/associations" | "/about/gallery" | "/about/management-team" | "/about/media" | "/about/quality-policy" | "/about/vision-mission" | "/admin" | "/admin/analytics" | "/admin/blogs" | "/admin/careers" | "/admin/case-studies" | "/admin/clients" | "/admin/cms" | "/admin/media" | "/admin/messages" | "/admin/newsletter" | "/admin/partners" | "/admin/products" | "/admin/testimonials" | "/auth/forgot-password" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/auth/verify-email" | "/careers" | "/careers/[slug]" | "/careers/apply" | "/certificate-verification" | "/contact" | "/engagements" | "/engagements/centre-of-excellence" | "/engagements/global-certifications" | "/engagements/global-certifications/[slug]" | "/engagements/placements" | "/engagements/professional-programs" | "/engagements/school" | "/engagements/university" | "/engagements/vocational" | "/events" | "/faculty" | "/future-academy" | "/highlights" | "/highlights/blogs" | "/highlights/blogs/[slug]" | "/highlights/case-studies" | "/highlights/case-studies/[slug]" | "/lms" | "/lms/login" | "/lms/purchase/[courseSlug]" | "/offline" | "/partner" | "/privacy" | "/products" | "/products/ai-future-academy" | "/products/appwizz-academy" | "/products/moxiemind" | "/products/science-lab" | "/refund-policy" | "/resources" | "/search" | "/success-stories" | "/terms"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/api/v1" | "/api/v1/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/about/advisory-board": {}
  "/about/associations": {}
  "/about/gallery": {}
  "/about/management-team": {}
  "/about/media": {}
  "/about/quality-policy": {}
  "/about/vision-mission": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/blogs": {}
  "/admin/careers": {}
  "/admin/case-studies": {}
  "/admin/clients": {}
  "/admin/cms": {}
  "/admin/media": {}
  "/admin/messages": {}
  "/admin/newsletter": {}
  "/admin/partners": {}
  "/admin/products": {}
  "/admin/testimonials": {}
  "/api/v1": {}
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/auth/verify-email": {}
  "/careers": {}
  "/careers/[slug]": { "slug": string; }
  "/careers/apply": {}
  "/certificate-verification": {}
  "/contact": {}
  "/engagements": {}
  "/engagements/centre-of-excellence": {}
  "/engagements/global-certifications": {}
  "/engagements/global-certifications/[slug]": { "slug": string; }
  "/engagements/placements": {}
  "/engagements/professional-programs": {}
  "/engagements/school": {}
  "/engagements/university": {}
  "/engagements/vocational": {}
  "/events": {}
  "/faculty": {}
  "/future-academy": {}
  "/highlights": {}
  "/highlights/blogs": {}
  "/highlights/blogs/[slug]": { "slug": string; }
  "/highlights/case-studies": {}
  "/highlights/case-studies/[slug]": { "slug": string; }
  "/lms": {}
  "/lms/login": {}
  "/lms/purchase/[courseSlug]": { "courseSlug": string; }
  "/offline": {}
  "/partner": {}
  "/privacy": {}
  "/products": {}
  "/products/ai-future-academy": {}
  "/products/appwizz-academy": {}
  "/products/moxiemind": {}
  "/products/science-lab": {}
  "/refund-policy": {}
  "/resources": {}
  "/search": {}
  "/success-stories": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
