// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/about/advisory-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/advisory-board">> = Specific
  const handler = {} as typeof import("../../app/about/advisory-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/associations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/associations">> = Specific
  const handler = {} as typeof import("../../app/about/associations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/gallery">> = Specific
  const handler = {} as typeof import("../../app/about/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/management-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/management-team">> = Specific
  const handler = {} as typeof import("../../app/about/management-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/media">> = Specific
  const handler = {} as typeof import("../../app/about/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/quality-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/quality-policy">> = Specific
  const handler = {} as typeof import("../../app/about/quality-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/vision-mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/vision-mission">> = Specific
  const handler = {} as typeof import("../../app/about/vision-mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blogs">> = Specific
  const handler = {} as typeof import("../../app/admin/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/careers">> = Specific
  const handler = {} as typeof import("../../app/admin/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/case-studies">> = Specific
  const handler = {} as typeof import("../../app/admin/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients">> = Specific
  const handler = {} as typeof import("../../app/admin/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cms">> = Specific
  const handler = {} as typeof import("../../app/admin/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media">> = Specific
  const handler = {} as typeof import("../../app/admin/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/newsletter">> = Specific
  const handler = {} as typeof import("../../app/admin/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/partners">> = Specific
  const handler = {} as typeof import("../../app/admin/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/testimonials">> = Specific
  const handler = {} as typeof import("../../app/admin/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../app/auth/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/careers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/[slug]">> = Specific
  const handler = {} as typeof import("../../app/careers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/careers/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/apply">> = Specific
  const handler = {} as typeof import("../../app/careers/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/certificate-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certificate-verification">> = Specific
  const handler = {} as typeof import("../../app/certificate-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/centre-of-excellence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/centre-of-excellence">> = Specific
  const handler = {} as typeof import("../../app/engagements/centre-of-excellence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/global-certifications/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/global-certifications/[slug]">> = Specific
  const handler = {} as typeof import("../../app/engagements/global-certifications/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/global-certifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/global-certifications">> = Specific
  const handler = {} as typeof import("../../app/engagements/global-certifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements">> = Specific
  const handler = {} as typeof import("../../app/engagements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/placements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/placements">> = Specific
  const handler = {} as typeof import("../../app/engagements/placements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/professional-programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/professional-programs">> = Specific
  const handler = {} as typeof import("../../app/engagements/professional-programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/school/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/school">> = Specific
  const handler = {} as typeof import("../../app/engagements/school/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/university/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/university">> = Specific
  const handler = {} as typeof import("../../app/engagements/university/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagements/vocational/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagements/vocational">> = Specific
  const handler = {} as typeof import("../../app/engagements/vocational/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faculty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faculty">> = Specific
  const handler = {} as typeof import("../../app/faculty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/future-academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/future-academy">> = Specific
  const handler = {} as typeof import("../../app/future-academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/highlights/blogs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/highlights/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../app/highlights/blogs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/highlights/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/highlights/blogs">> = Specific
  const handler = {} as typeof import("../../app/highlights/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/highlights/case-studies/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/highlights/case-studies/[slug]">> = Specific
  const handler = {} as typeof import("../../app/highlights/case-studies/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/highlights/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/highlights/case-studies">> = Specific
  const handler = {} as typeof import("../../app/highlights/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/highlights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/highlights">> = Specific
  const handler = {} as typeof import("../../app/highlights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lms/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/login">> = Specific
  const handler = {} as typeof import("../../app/lms/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms">> = Specific
  const handler = {} as typeof import("../../app/lms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lms/purchase/[courseSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/purchase/[courseSlug]">> = Specific
  const handler = {} as typeof import("../../app/lms/purchase/[courseSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../app/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/ai-future-academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/ai-future-academy">> = Specific
  const handler = {} as typeof import("../../app/products/ai-future-academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/appwizz-academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/appwizz-academy">> = Specific
  const handler = {} as typeof import("../../app/products/appwizz-academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/moxiemind/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/moxiemind">> = Specific
  const handler = {} as typeof import("../../app/products/moxiemind/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/science-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/science-lab">> = Specific
  const handler = {} as typeof import("../../app/products/science-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/success-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success-stories">> = Specific
  const handler = {} as typeof import("../../app/success-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
