import { Router } from 'express';
import analyticsRoutes from './analyticsRoutes';
import authRoutes from './authRoutes';
import blogRoutes from './blogRoutes';
import careerRoutes from './careerRoutes';
import caseStudyRoutes from './caseStudyRoutes';
import clientRoutes from './clientRoutes';
import cmsRoutes from './cmsRoutes';
import commentRoutes from './commentRoutes';
import contactRoutes from './contactRoutes';
import eventRoutes from './eventRoutes';
import facultyRoutes from './facultyRoutes';
import inquiryRoutes from './inquiryRoutes';
import mediaRoutes from './mediaRoutes';
import newsletterRoutes from './newsletterRoutes';
import notificationRoutes from './notificationRoutes';
import productRoutes from './productRoutes';
import resourceRoutes from './resourceRoutes';
import searchRoutes from './searchRoutes';
import successStoryRoutes from './successStoryRoutes';
import testimonialRoutes from './testimonialRoutes';
import timelineRoutes from './timelineRoutes';
import userRoutes from './userRoutes';

const router = Router();
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/blogs', blogRoutes);
router.use('/products', productRoutes);
router.use('/careers', careerRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/clients', clientRoutes);
router.use('/contacts', contactRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/inquiries', inquiryRoutes);
router.use('/case-studies', caseStudyRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/media', mediaRoutes);
router.use('/search', searchRoutes);
router.use('/cms', cmsRoutes);
router.use('/comments', commentRoutes);
router.use('/resources', resourceRoutes);
router.use('/events', eventRoutes);
router.use('/success-stories', successStoryRoutes);
router.use('/faculty', facultyRoutes);
router.use('/timelines', timelineRoutes);
router.use('/notifications', notificationRoutes);

export default router;
