var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/refund-policy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3224e5a4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f0343b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87cd44b0._.js")
R.c("server/chunks/ssr/app_0ef037c1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__047e758f._.js")
R.c("server/chunks/ssr/lib_utils_ts_78807e9c._.js")
R.c("server/chunks/ssr/_af918847._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__07aef32e._.js")
R.c("server/chunks/ssr/_993f36f0._.js")
R.c("server/chunks/ssr/_c9608d70._.js")
R.m(55339)
R.m(33844)
module.exports=R.m(33844).exports
