export type LmsProfessionalOffering = {
  id: string;
  title: string;
  type: "Professional Program" | "Specialization";
  buildExpertise: string[];
  youWillLearn: string[];
  industryOpportunities: string[];
  careerPathways: string[];
  capstone: string;
};

const PROFESSIONAL_PROGRAMS: LmsProfessionalOffering[] = [
  {
    id: "professional-program-robotic-process-automation",
    type: "Professional Program",
    title: "CITIS Professional Program in Robotic Process Automation",
    buildExpertise: [
      "RPA fundamentals and automation",
      "UiPath, Blue Prism, and Automation Anywhere",
      "Bot development and workflow design",
      "AI, NLP, and OCR-enabled automation",
      "RPA governance, security, and compliance",
      "Process mining and intelligent process automation",
    ],
    youWillLearn: [
      "Design and develop automation workflows",
      "Build and manage software bots",
      "Integrate automation with databases, APIs, and enterprise applications",
      "Apply AI-enabled automation techniques",
      "Evaluate automation performance and business impact",
    ],
    industryOpportunities: ["Banking", "Healthcare", "IT Services", "Manufacturing", "BFSI", "Shared Services", "Business Operations"],
    careerPathways: ["RPA Developer", "Automation Engineer", "RPA Consultant", "Automation Analyst", "Process Analyst", "Intelligent Automation Associate"],
    capstone: "Industry-oriented RPA automation project",
  },
  {
    id: "professional-program-cybersecurity",
    type: "Professional Program",
    title: "CITIS Professional Program in Cybersecurity",
    buildExpertise: [
      "Cybersecurity fundamentals and threat intelligence",
      "Ethical hacking and penetration testing",
      "Network security and cryptography",
      "Digital forensics and incident response",
      "Cloud security and DevSecOps",
      "Cyber law, GRC, and security compliance",
    ],
    youWillLearn: [
      "Identify cyber threats and vulnerabilities",
      "Perform basic security assessments",
      "Understand penetration-testing methodologies",
      "Apply network and cryptographic security concepts",
      "Support incident response and forensic investigations",
      "Understand cybersecurity governance and compliance",
    ],
    industryOpportunities: ["IT Services", "BFSI", "Healthcare", "Government", "E-Commerce", "Telecom", "Critical Infrastructure"],
    careerPathways: ["Cybersecurity Analyst", "Ethical Hacker", "SOC Analyst", "Security Consultant", "Penetration Testing Associate", "Forensic Investigator"],
    capstone: "Industry-oriented cybersecurity project",
  },
  {
    id: "professional-program-blockchain-technologies",
    type: "Professional Program",
    title: "CITIS Professional Program in Blockchain Technologies",
    buildExpertise: [
      "Blockchain and distributed ledger technology",
      "Cryptography and consensus mechanisms",
      "Smart contracts and Solidity",
      "DApps and tokenisation",
      "Ethereum and Hyperledger",
      "Enterprise blockchain and Web3",
    ],
    youWillLearn: [
      "Understand blockchain architectures",
      "Develop basic smart contracts",
      "Understand DApp development",
      "Apply blockchain security principles",
      "Explore enterprise blockchain solutions",
      "Analyse blockchain use cases across industries",
    ],
    industryOpportunities: ["FinTech", "Banking", "Supply Chain", "Healthcare", "Digital Payments", "Enterprise Technology", "Web3"],
    careerPathways: ["Blockchain Developer", "Smart Contract Developer", "Blockchain Engineer", "DApp Developer", "Blockchain Consultant", "Blockchain Solutions Associate"],
    capstone: "Industry-oriented blockchain solutions project",
  },
  {
    id: "professional-program-data-analytics-business-intelligence",
    type: "Professional Program",
    title: "CITIS Professional Program in Data Analytics & Business Intelligence",
    buildExpertise: [
      "Data analytics fundamentals",
      "Data cleaning and preprocessing",
      "Exploratory data analysis",
      "Statistics and predictive analytics",
      "Power BI, Tableau, and data visualisation",
      "Big data and cloud analytics",
    ],
    youWillLearn: [
      "Collect, clean, and analyse datasets",
      "Perform exploratory analysis",
      "Create dashboards and reports",
      "Apply predictive analytics",
      "Communicate insights through data storytelling",
      "Support data-driven business decisions",
    ],
    industryOpportunities: ["Finance", "Healthcare", "Retail", "Marketing", "E-Commerce", "Technology", "Consulting"],
    careerPathways: ["Data Analyst", "Business Intelligence Analyst", "Business Analyst", "Reporting Analyst", "Marketing Analyst", "Analytics Associate"],
    capstone: "Industry-oriented data analytics and business intelligence project",
  },
  {
    id: "professional-program-it-infrastructure-management",
    type: "Professional Program",
    title: "CITIS Professional Program in IT Infrastructure Management",
    buildExpertise: [
      "IT infrastructure and network management",
      "Cloud computing and virtualisation",
      "Server administration",
      "Data centre management",
      "Cybersecurity and IT governance",
      "ITSM, ITIL, and infrastructure automation",
    ],
    youWillLearn: [
      "Understand enterprise infrastructure architecture",
      "Work with networks, servers, and virtual environments",
      "Understand cloud infrastructure",
      "Apply infrastructure security practices",
      "Understand IT service management",
      "Support infrastructure monitoring and optimisation",
    ],
    industryOpportunities: ["IT Services", "Data Centres", "Cloud Services", "Managed Services", "Enterprise IT", "Telecommunications"],
    careerPathways: ["Network Engineer", "Cloud Administrator", "Systems Administrator", "IT Infrastructure Engineer", "IT Operations Associate", "ITSM Consultant"],
    capstone: "Industry-oriented IT infrastructure management project",
  },
  {
    id: "professional-program-cloud-computing",
    type: "Professional Program",
    title: "CITIS Professional Program in Cloud Computing",
    buildExpertise: [
      "Cloud fundamentals and virtualisation",
      "AWS, Microsoft Azure, and Google Cloud",
      "Cloud infrastructure and networking",
      "Cloud security and IAM",
      "DevOps, CI/CD, and infrastructure as code",
      "Cloud AI, big data, and IoT",
    ],
    youWillLearn: [
      "Understand cloud architectures",
      "Work with cloud compute, storage, and networking",
      "Apply cloud security principles",
      "Understand DevOps and automation",
      "Work with containers and IaC concepts",
      "Understand cloud-based AI and data services",
    ],
    industryOpportunities: ["Cloud Services", "IT Services", "SaaS", "Enterprise Technology", "DevOps", "Digital Transformation"],
    careerPathways: ["Cloud Engineer", "Cloud Administrator", "DevOps Engineer", "Cloud Security Associate", "Cloud Operations Engineer", "Solutions Associate"],
    capstone: "Industry-oriented cloud computing project",
  },
  {
    id: "professional-program-extended-reality",
    type: "Professional Program",
    title: "CITIS Professional Program in Extended Reality",
    buildExpertise: [
      "AR, VR, MR, and XR fundamentals",
      "3D modelling and animation",
      "Unity and Unreal Engine",
      "WebXR and immersive applications",
      "Spatial computing and interaction design",
      "AI, IoT, blockchain, and metaverse applications",
    ],
    youWillLearn: [
      "Understand AR, VR, and XR ecosystems",
      "Work with immersive development platforms",
      "Create and work with 3D assets",
      "Understand immersive UX/UI",
      "Explore spatial computing",
      "Design basic XR applications and experiences",
    ],
    industryOpportunities: ["Gaming", "Education", "Healthcare", "Retail", "Manufacturing", "Real Estate", "Training", "Entertainment"],
    careerPathways: ["XR Developer", "AR/VR Developer", "3D Content Developer", "Immersive Experience Designer", "XR UX/UI Designer", "Game Developer", "Metaverse Experience Associate"],
    capstone: "Industry-oriented extended reality experience",
  },
  {
    id: "professional-program-data-science",
    type: "Professional Program",
    title: "CITIS Professional Program in Data Science",
    buildExpertise: [
      "Python, R, and SQL",
      "Data wrangling and EDA",
      "Machine learning",
      "Deep learning and neural networks",
      "NLP and computer vision",
      "Big data and cloud computing",
    ],
    youWillLearn: [
      "Prepare and analyse datasets",
      "Develop predictive models",
      "Apply machine-learning techniques",
      "Understand deep-learning applications",
      "Work with data visualisation and BI",
      "Understand cloud-based data pipelines",
    ],
    industryOpportunities: ["Technology", "Finance", "Healthcare", "Retail", "E-Commerce", "Marketing", "IoT"],
    careerPathways: ["Data Scientist", "Data Analyst", "Machine Learning Associate", "AI Analyst", "BI Analyst", "Data Engineer – Entry Level", "AI Solutions Associate"],
    capstone: "Industry-oriented data science project",
  },
  {
    id: "professional-program-generative-artificial-intelligence",
    type: "Professional Program",
    title: "CITIS Professional Program in Generative Artificial Intelligence",
    buildExpertise: [
      "Generative AI fundamentals",
      "Deep learning and neural networks",
      "Large language models and prompt engineering",
      "GANs and diffusion models",
      "AI-generated text, image, video, and music",
      "Responsible AI, security, and deployment",
    ],
    youWillLearn: [
      "Understand generative AI technologies",
      "Work with LLM-based applications",
      "Apply prompt engineering approaches",
      "Explore AI-generated multimedia",
      "Understand AI security and responsible AI",
      "Develop a generative AI-based project",
    ],
    industryOpportunities: ["Technology", "Marketing", "Media", "Advertising", "Healthcare", "Finance", "Gaming", "Creative Industries"],
    careerPathways: ["Generative AI Associate", "Prompt Engineer", "AI Application Developer", "AI Content Specialist", "AI Automation Specialist", "AI Solutions Associate"],
    capstone: "Industry-oriented generative AI project",
  },
  {
    id: "professional-program-artificial-intelligence-machine-learning",
    type: "Professional Program",
    title: "CITIS Professional Program in Artificial Intelligence & Machine Learning",
    buildExpertise: [
      "AI and machine learning fundamentals",
      "Supervised and unsupervised learning",
      "Neural networks and deep learning",
      "NLP and computer vision",
      "Cloud-based AI deployment",
      "AI ethics, XAI, and governance",
    ],
    youWillLearn: [
      "Develop basic ML models",
      "Apply classification, regression, and clustering",
      "Understand neural networks",
      "Work with NLP and computer vision applications",
      "Understand cloud AI deployment",
      "Evaluate AI solutions from ethical and governance perspectives",
    ],
    industryOpportunities: ["Technology", "Healthcare", "Finance", "Robotics", "E-Commerce", "Smart Cities", "Automation"],
    careerPathways: ["AI Engineer", "Machine Learning Associate", "Data Scientist", "AI Analyst", "ML Application Developer", "AI Product Associate"],
    capstone: "Industry-oriented AI and machine learning project",
  },
  {
    id: "professional-program-full-stack-development",
    type: "Professional Program",
    title: "CITIS Professional Program in Full Stack Development",
    buildExpertise: [
      "HTML, CSS, and JavaScript",
      "React, Angular, and Vue",
      "Node.js and server-side development",
      "SQL, MongoDB, and databases",
      "APIs, Git, Docker, and CI/CD",
      "Cloud deployment and microservices",
    ],
    youWillLearn: [
      "Build responsive web applications",
      "Develop front-end and back-end components",
      "Work with databases and APIs",
      "Use Git and DevOps workflows",
      "Deploy applications on cloud platforms",
      "Apply web security and scalability principles",
    ],
    industryOpportunities: ["Software", "IT Services", "Startups", "SaaS", "E-Commerce", "Digital Platforms", "Enterprise Technology"],
    careerPathways: ["Full Stack Developer", "Software Engineer", "Front-End Developer", "Back-End Developer", "DevOps Engineer", "Cloud Application Developer"],
    capstone: "Industry-oriented full stack web application",
  },
  {
    id: "professional-program-digital-marketing-ecommerce",
    type: "Professional Program",
    title: "CITIS Professional Program in Digital Marketing & E-Commerce",
    buildExpertise: [
      "Digital marketing fundamentals",
      "SEO and SEM",
      "Social media and content marketing",
      "E-commerce management",
      "Performance marketing and analytics",
      "CRM, automation, and AI marketing",
    ],
    youWillLearn: [
      "Develop digital marketing strategies",
      "Execute SEO and paid campaigns",
      "Manage social media campaigns",
      "Understand e-commerce operations",
      "Analyse digital campaign performance",
      "Apply marketing automation and AI tools",
    ],
    industryOpportunities: ["Digital Agencies", "E-Commerce", "D2C", "Retail", "Advertising", "Media", "Startups", "Corporate Marketing"],
    careerPathways: ["Digital Marketing Executive", "SEO Analyst", "Performance Marketing Associate", "E-Commerce Executive", "Content Marketing Associate", "Growth Marketing Associate"],
    capstone: "Industry-oriented digital marketing and e-commerce campaign",
  },
];

const SPECIALIZATIONS: LmsProfessionalOffering[] = [
  {
    id: "specialization-marketing-brand-management",
    type: "Specialization",
    title: "CITIS Specialization in Marketing & Brand Management",
    buildExpertise: [
      "Marketing fundamentals and consumer behaviour",
      "Branding and positioning",
      "Digital and social media marketing",
      "Marketing analytics and AI",
      "Sales and negotiation",
      "Customer experience and CRM",
    ],
    youWillLearn: [
      "Understand consumer behaviour and marketing fundamentals",
      "Build distinctive brand positioning",
      "Plan digital and social media campaigns",
      "Use marketing analytics and AI",
      "Apply sales and negotiation techniques",
      "Manage customer experience and CRM",
    ],
    industryOpportunities: ["FMCG", "Retail", "Technology", "Healthcare", "Finance", "Media", "E-Commerce", "Startups"],
    careerPathways: ["Marketing Executive", "Brand Executive", "Brand Strategist", "Digital Marketing Associate", "Marketing Analyst", "Sales Consultant", "CRM Executive"],
    capstone: "Industry-oriented marketing and brand management project",
  },
  {
    id: "specialization-entrepreneurship-startup-development",
    type: "Specialization",
    title: "CITIS Specialization in Entrepreneurship & Startup Development",
    buildExpertise: [
      "Entrepreneurship and business models",
      "Lean startup and business validation",
      "Finance and startup funding",
      "Marketing and customer acquisition",
      "Leadership and negotiation",
      "Technology and growth hacking",
    ],
    youWillLearn: [
      "Identify opportunities and shape business models",
      "Validate ideas through lean startup methods",
      "Understand startup finance and funding",
      "Acquire customers and build market traction",
      "Lead teams and negotiate with stakeholders",
      "Use technology and growth-hacking approaches",
    ],
    industryOpportunities: ["Startups", "MSMEs", "Family Business", "Consulting", "Incubators", "Innovation Teams", "New Ventures"],
    careerPathways: ["Entrepreneur", "Startup Associate", "Business Consultant", "Business Development Executive", "Growth Strategist", "Innovation Associate", "Startup Operations Executive"],
    capstone: "Industry-oriented startup development project",
  },
  {
    id: "specialization-design-thinking-innovation",
    type: "Specialization",
    title: "CITIS Specialization in Design Thinking & Innovation",
    buildExpertise: [
      "Design thinking frameworks",
      "Empathy and user research",
      "Ideation and creative problem solving",
      "Prototyping and testing",
      "Service design and customer experience",
      "Innovation strategy",
    ],
    youWillLearn: [
      "Conduct empathy-led user research",
      "Define meaningful user and business problems",
      "Generate ideas through creative problem solving",
      "Prototype and test solutions",
      "Apply service design and customer experience methods",
      "Build an innovation strategy",
    ],
    industryOpportunities: ["Technology", "Consulting", "Product Development", "Healthcare", "Education", "Design", "Social Innovation"],
    careerPathways: ["Innovation Associate", "UX Designer", "Product Associate", "Innovation Strategist", "Business Consultant", "Design Research Associate", "Service Design Associate"],
    capstone: "Industry-oriented design thinking and innovation project",
  },
  {
    id: "specialization-operations-supply-chain-management",
    type: "Specialization",
    title: "CITIS Specialization in Operations & Supply Chain Management",
    buildExpertise: [
      "Business operations and process management",
      "Supply chain and logistics",
      "Procurement and inventory",
      "Lean management and Six Sigma",
      "ERP, AI, and automation",
      "Project and risk management",
    ],
    youWillLearn: [
      "Map and improve business processes",
      "Coordinate supply chain and logistics activities",
      "Manage procurement and inventory decisions",
      "Apply Lean and Six Sigma improvement methods",
      "Use ERP, AI, and automation in operations",
      "Manage projects and operational risk",
    ],
    industryOpportunities: ["Manufacturing", "Retail", "E-Commerce", "Logistics", "Healthcare", "FMCG", "Warehousing", "Distribution"],
    careerPathways: ["Operations Executive", "Operations Analyst", "Supply Chain Analyst", "Logistics Executive", "Procurement Associate", "Process Improvement Associate", "Project Coordinator"],
    capstone: "Industry-oriented operations and supply chain project",
  },
  {
    id: "specialization-cybersecurity",
    type: "Specialization",
    title: "CITIS Specialization in Cybersecurity",
    buildExpertise: [
      "Threat intelligence and threat hunting",
      "Ethical hacking and penetration testing",
      "Network security and cryptography",
      "Cloud security and DevSecOps",
      "Cyber law and GRC",
      "Security auditing and risk management",
    ],
    youWillLearn: [
      "Hunt threats across enterprise environments",
      "Apply ethical hacking and penetration-testing methods",
      "Use network and cryptographic security concepts",
      "Secure cloud environments and DevSecOps workflows",
      "Understand cyber law and GRC requirements",
      "Support security audits and risk management",
    ],
    industryOpportunities: ["IT", "BFSI", "Government", "Healthcare", "Cloud Services", "Consulting", "Enterprise Security"],
    careerPathways: ["Cybersecurity Analyst", "SOC Analyst", "Security Operations Associate", "Penetration Testing Associate", "Cloud Security Associate", "Cyber Risk Associate", "Security Consultant"],
    capstone: "Industry-oriented advanced cybersecurity project",
  },
  {
    id: "specialization-data-science",
    type: "Specialization",
    title: "CITIS Specialization in Data Science",
    buildExpertise: [
      "Data science fundamentals",
      "Python and R",
      "Data wrangling and EDA",
      "Machine learning",
      "Data visualisation and BI",
      "Big data and cloud computing",
    ],
    youWillLearn: [
      "Apply data science fundamentals to real datasets",
      "Use Python and R for analysis",
      "Wrangle data and perform exploratory analysis",
      "Build and evaluate machine-learning models",
      "Communicate insights through visualisation and BI",
      "Understand big data and cloud-based processing",
    ],
    industryOpportunities: ["Finance", "Healthcare", "Retail", "E-Commerce", "Technology", "Marketing", "IoT"],
    careerPathways: ["Data Analyst", "BI Analyst", "Data Science Associate", "Junior Data Scientist", "ML Associate", "Data Visualisation Analyst", "AI Analytics Associate"],
    capstone: "Industry-oriented data science project",
  },
  {
    id: "specialization-data-analytics-visualization",
    type: "Specialization",
    title: "CITIS Specialization in Data Analytics & Visualization",
    buildExpertise: [
      "Data analytics and business intelligence",
      "Data collection and cleaning",
      "Statistics and exploratory data analysis",
      "Power BI and Tableau",
      "Data storytelling",
      "Predictive analytics and AI",
    ],
    youWillLearn: [
      "Collect and clean business data",
      "Apply statistical and exploratory analysis",
      "Create interactive Power BI and Tableau dashboards",
      "Communicate insights through data storytelling",
      "Apply predictive analytics and AI",
      "Support clear, evidence-based business decisions",
    ],
    industryOpportunities: ["Finance", "Healthcare", "Retail", "Marketing", "E-Commerce", "Technology", "Consulting"],
    careerPathways: ["Data Analyst", "BI Analyst", "Data Visualisation Analyst", "Business Analyst", "Marketing Analyst", "Reporting Analyst", "Analytics Associate"],
    capstone: "Industry-oriented data analytics and visualisation project",
  },
];

export { PROFESSIONAL_PROGRAMS, SPECIALIZATIONS };
export const LMS_PROFESSIONAL_OFFERINGS = [...PROFESSIONAL_PROGRAMS, ...SPECIALIZATIONS];