"use client";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
const base=(process.env.NEXT_PUBLIC_API_BASE_URL?.trim()||(process.env.NODE_ENV==="production"?"https://api.citisinfotech.in/api/v1":"/api/v1")).replace(/\/$/,"");
async function request<T>(path:string, init?:RequestInit){const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");const r=await fetch(`${base}${path}`,{...init,credentials:"include",headers});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.message||"Request failed.");return p as T;}
type Row={id:string;name?:string;code?:string;status?:string;start_date?:string;end_date?:string};
export default function AcademicStructurePage(){
 const [kind,setKind]=useState("faculties"),[rows,setRows]=useState<Row[]>([]),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[institutions,setInstitutions]=useState<Row[]>([]),[institutionId,setInstitutionId]=useState("");
 const load=()=>request<{data:Row[]}>(kind==="programmes"?`/programmes${institutionId?`?institutionId=${institutionId}`:""}`:`/academic/${kind}${institutionId?`?institutionId=${institutionId}`:""}`).then(x=>setRows(x.data||[])).catch(()=>setError("Unable to load academic records."));
 useEffect(()=>{request<{data:Row[]}>("/institutions/scoped-options").then(x=>{setInstitutions(x.data||[]);if(!institutionId&&x.data?.[0])setInstitutionId(x.data[0].id);}).catch(()=>setError("Unable to load institutions in your scope."));},[]);
 useEffect(load,[kind,institutionId]);
 async function create(e:FormEvent){e.preventDefault();setError("");if(!institutionId){setError("Select an institution.");return;}const body=kind==="semesters"?{institutionId,name,code,startDate:new Date().toISOString().slice(0,10),endDate:new Date(Date.now()+86400000).toISOString().slice(0,10)}:{institutionId,name,code};try{await request(kind==="programmes"?"/programmes":`/academic/${kind}`,{method:"POST",body:JSON.stringify(body)});setName("");setCode("");load();}catch(e){setError(e instanceof Error?e.message:"Create failed.");}}
 return <main style={{maxWidth:1000,margin:"40px auto",padding:24,fontFamily:"sans-serif"}}><h1>Academic structure</h1><p>Manage scoped faculties, departments, semesters, and course offerings without changing catalogue courses.</p><label>Institution <select value={institutionId} onChange={e=>setInstitutionId(e.target.value)} required><option value="">Select institution</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><nav aria-label="Academic structure resources">{["programmes","faculties","departments","semesters","course-offerings"].map(x=><button key={x} onClick={()=>setKind(x)} aria-current={kind===x?"page":undefined} style={{margin:4,padding:10}}>{x.replace("-"," ")}</button>)}</nav><form onSubmit={create} style={{display:"flex",gap:8,margin:"24px 0"}}><input aria-label="Name" placeholder="Name" value={name} onChange={e=>setName(e.target.value)} required/><input aria-label="Code" placeholder="Code" value={code} onChange={e=>setCode(e.target.value)} required/><button type="submit">Create</button></form>{error&&<p role="alert">{error}</p>}<ul>{rows.map(r=><li key={r.id}>{r.name||r.code} {r.code&&`(${r.code})`} — {r.status}</li>)}</ul></main>;
}